Add swap between channel easy
canonical-web-and-design/charmhub.io pull request #478
Opened 2020-11-03 13:39 UTC by tbille

## Done

- Refactor code for channel map
- Refactor code for details header page `get_package`
- Add ability to get the data for a specific channel
- Add back the channel map in header

/!\ Not done in this PR: swapping the channel via the channel map

## QA

- Use the staging API:
```
On file .env.local:

CHARMSTORE_API_URL=https://api.staging.snapcraft.io/
```
- `dotrun`
- http://0.0.0.0:8045/activemq?channel=stable
- Navigate in the pages and make sure that the channel doesn't change (see URL)
- http://0.0.0.0:8045/activemq
- Should work as usual too

Unfortunately there are no charms with different data between channels for now....

2020-11-03 13:39 UTC, webteam-app commented
Demo starting at https://charmhub-io-478.demos.haus

2020-11-04 10:38 UTC, anthonydillon requested changes
Code looks good but one QA issue.

## QA
- If you are on a tab such as the action tab and change channel you jump back to the overview when I would expect to remain on the actions

2020-11-04 11:26 UTC, tbille commented
Good catch. Behaviour updated @anthonydillon

2020-11-04 12:18 UTC, anthonydillon approved these changes
Nice one :+1:

2020-11-04 12:18 UTC, merged