Add feature charms
canonical-web-and-design/charmhub.io pull request #496
Opened 2020-11-04 21:10 UTC by tbille

## Done

- Added feature charms functionnality
- The list is a random list of charms handpicked. Once we have the import and the actual charms to feature then replace the current list:

```
FEATURED_CHARMS = [
    "ceph",
    "eclipse-che",
    "ghost",
    "ibm-java",
    "kafka",
]
```

## QA

- `dotrun`
- http://0.0.0.0:8045
- By default the first charms should be the featured ones
- Play with the filters
- Make sure the charms appear once.

## Issue / Card

Fixes #460

2020-11-04 21:10 UTC, webteam-app commented
Demo starting at https://charmhub-io-496.demos.haus

2020-11-04 21:16 UTC, hatched commented
QA Notes:
- [ ] When selecting the platform "Kubernetes" sorting by "featured" I don't see Eclipse at the start.
- [ ] Hitting the back button changes the URL
  from: `https://charmhub-io-496.demos.haus/?sort=featured&platform=all`
  to: `https://charmhub-io-496.demos.haus/?sort=featured&platform=all` 
but the page doesn't update

2020-11-04 21:22 UTC, tbille commented
>  When selecting the platform "Kubernetes" sorting by "featured" I don't see Eclipse at the start.

The import of charms and their complete metadata is not done yet. Eclispe for us appears not as a Kubernetes charm, it's known and not related with this code.

> Hitting the back button changes the URL
>  from: https://charmhub-io-496.demos.haus/?sort=featured&platform=all
> to: https://charmhub-io-496.demos.haus/?sort=featured&platform=all
> but the page doesn't update

The 2 links are the same here. :)

2020-11-04 21:24 UTC, hatched commented
Oops sorry bad copy/paste, but the back button is broken no matter what you change in the filters, I guess that's probably unrelated to this branch.

2020-11-04 21:25 UTC, hatched commented
I've updated the label as none of these issues appear to be related to this PR.

2020-11-05 08:43 UTC, anthonydillon requested changes
Works well, one comment on the code and I think if we are supporting by featured them we should add a label to the card to make it clear. Could be a follow up.

2020-11-05 08:43 UTC, anthonydillon commented on templates/store.html
> +        <label for="name-asc">Name A/Z</label>
You mean Featured

2020-11-05 09:14 UTC, tbille commented on templates/store.html
> +        <label for="name-asc">Name A/Z</label>
oops.
Fixed

2020-11-05 16:35 UTC, jpmartinspt approved these changes

2020-11-05 17:35 UTC, merged