Add suru pattern to details pages
canonical-web-and-design/charmhub.io pull request #671
Opened 2020-11-18 17:51 UTC by steverydz

## Done

Added light suru pattern to detail pages

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://localhost:8045/postgresql-k8s
- Check that there is a light grey suru on the header strip

## Issue / Card

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1688

2020-11-18 17:51 UTC, webteam-app commented
Demo starting at https://charmhub-io-671.demos.haus

2020-11-18 23:44 UTC, anthonydillon requested changes
Suggestions in code

2020-11-18 23:44 UTC, anthonydillon commented on static/sass/styles.scss
> +.p-strip--charmhub-light {
Could you move these styles to a strip SCSS file. Styles here are for bugs and hacks that are to be removed.

Maybe `.p-strip--suru-light` or extend the existing strip with `.p-strip--light.has-suru`?

2020-11-19 09:08 UTC, steverydz commented
@anthonydillon fixed

2020-11-19 09:25 UTC, anthonydillon requested changes
Some small suggestions in the code

2020-11-19 09:25 UTC, anthonydillon commented on static/sass/_pattern_p-strip.scss
> +  .has-suru {
Sorry, but its probably worth scoping this to just strips using `[class*='p-strip']` for example https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_patterns_strip.scss#L103.

2020-11-19 09:25 UTC, anthonydillon commented on static/sass/_pattern_p-strip.scss
> +    @media screen and (max-width: $breakpoint-medium) {
Why not wrap all the styles above in a `@media screen and (min-width: $breakpoint-medium)` and then you are not overriding and leaving `background-position` styling applied.

2020-11-19 10:03 UTC, steverydz commented
@anthonydillon ok, fixed

2020-11-19 11:24 UTC, anthonydillon approved these changes
LGTM :+1:

2020-11-19 11:24 UTC, merged